# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new iOS Dev app to Firebase AppDistribution"
  lane :submit_ios_dev_app do
    match(
      type: "adhoc",
      app_identifier: ['com.labhouse.rankai.dev'],
      readonly: true,
    )
    build_number = Time.now.strftime("%Y%m%d%H")
    sh "flutter build ios --release --dart-define-from-file assets/config/dev.json --flavor dev --build-name #{flutter_version()["version_name"]} --build-number #{build_number} --no-codesign"
    build_app(
      scheme: "dev",
      workspace: "Runner.xcworkspace",
      export_method: "ad-hoc",
      export_options: {
        provisioningProfiles: {
          "com.labhouse.rankai.dev" => "match AdHoc com.labhouse.rankai.dev"
        }
      }
    )
    firebase_app_distribution(
      app: "1:610327491508:ios:23b7cdbc28a6cf7c57f8e1",
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      ipa_path: ENV['IPA_OUTPUT_PATH'],
      groups: "ios"
    )
  end

  desc "Generate dev certificate and provisionning profile"
  lane :generate_dev_certificates do
    match(
      type: "development",
      app_identifier: ['com.labhouse.rankai.dev'],
      readonly: false,
    )
  end

  desc "Generate adhoc certificate and provisionning profile"
  lane :generate_adhoc_certificates do
    match(
      type: "adhoc",
      app_identifier: ['com.labhouse.rankai.dev'],
      readonly: false,
    )
  end

  desc "Get dev development certificate and provisionning profile"
  lane :get_dev_development_certificates do
    match(
      type: "development",
      app_identifier: ['com.labhouse.rankai.dev'],
      readonly: true,
    )
  end

  desc "Get dev adhoc certificate and provisionning profile"
  lane :get_dev_adhoc_certificates do
    match(
      type: "adhoc",
      app_identifier: ['com.labhouse.rankai.dev'],
      readonly: true,
    )
  end

  desc "Register new device"
  lane :register_new_device do
    device_name = prompt(text: "Enter the device name: ")
    device_udid = prompt(text: "Enter the device UDID: ")
    device_hash = {}
    device_hash[device_name] = device_udid
    register_devices(devices: device_hash)
    match(
      type: "development",
      app_identifier: ['com.labhouse.rankai.dev'],
      readonly: false,
      force: true,
    )
    match(
      type: "adhoc",
      app_identifier: ['com.labhouse.rankai.dev'],
      readonly: false,
      force: true,
    )
  end
end
